/**
 * Cloudflare Worker entry point.
 *
 * The site is still a static Astro build — this Worker exists for exactly one
 * reason: to accept POSTs from /takedown/ so the archive can be reachable for
 * corrections and removal requests WITHOUT publishing a personal email address
 * on a public page. Everything else is delegated straight back to the static
 * asset server.
 *
 * Because `assets` is configured alongside `main`, Cloudflare serves matching
 * static assets WITHOUT invoking this Worker at all. This code therefore only
 * runs for paths that aren't files in dist/ — in practice, /api/*.
 *
 * Minimal hand-rolled types below rather than @cloudflare/workers-types: this
 * file is inside the Astro project's tsconfig `include`, and the Workers DOM
 * type overrides collide with Astro's strict DOM lib.
 */

interface D1Result<T = unknown> {
  results: T[];
}

interface D1PreparedStatement {
  bind(...values: unknown[]): D1PreparedStatement;
  run(): Promise<unknown>;
  all<T = unknown>(): Promise<D1Result<T>>;
}

interface D1Database {
  prepare(query: string): D1PreparedStatement;
}

interface AssetsBinding {
  fetch(request: Request): Promise<Response>;
}

interface Env {
  ASSETS: AssetsBinding;
  TAKEDOWNS: D1Database;
}

/** Accepted values for the request `kind` field. */
const KINDS = new Set(["takedown", "correction", "context", "other"]);

/**
 * Field caps. These are generous for a human and hostile to anyone trying to
 * push megabytes into the row — D1 rows are cheap but not free, and an
 * unbounded TEXT column on a public endpoint is an obvious abuse vector.
 */
const MAX_MESSAGE = 4000;
const MAX_SHORT_FIELD = 300;

/**
 * Crude global flood cap: total submissions accepted per minute across all
 * callers. This is deliberately NOT per-IP — we don't store IPs (see below),
 * so we can't rate limit by them. It won't stop a determined attacker, but it
 * bounds the damage from a naive script. Turnstile is the real fix and is the
 * intended next step; see docs.
 */
const MAX_PER_MINUTE = 20;

/**
 * Served only to no-JavaScript form submissions. Deliberately self-contained
 * and inline-styled: it is generated by the Worker, not by the Astro build, so
 * it has no access to the hashed /_astro/*.css bundle.
 */
const CONFIRMATION_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Request received — 20.07.2026</title>
<style>
  html{color-scheme:dark}
  body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;
       background:#000;color:#fff;font:16px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
  main{max-width:32rem;padding:2rem;text-align:center}
  h1{font-size:1.25rem;margin:0 0 .75rem}
  p{color:#a8a8a8;margin:0 0 1.5rem}
  a{color:#0095f6}
</style></head>
<body><main>
<h1>Request received</h1>
<p>Thank you. This has been logged and will be reviewed. If you left a way to reach you, you may get a reply.</p>
<p><a href="/">Return to the archive</a></p>
</main></body></html>`;

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}

function clean(value: unknown, max: number): string {
  if (typeof value !== "string") return "";
  // Strip control characters (except newline/tab) before length-capping.
  return value
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "")
    .trim()
    .slice(0, max);
}

async function handleTakedown(request: Request, env: Env): Promise<Response> {
  if (request.method !== "POST") {
    return json({ ok: false, error: "Method not allowed." }, 405);
  }

  // Same-origin guard. Not a security boundary (Origin is forgeable outside a
  // browser), but it stops the endpoint being trivially posted to from another
  // site's page using a visitor's browser.
  const origin = request.headers.get("origin");
  if (origin) {
    const allowed = new URL(request.url).origin;
    if (origin !== allowed) {
      return json({ ok: false, error: "Cross-origin requests are not accepted." }, 403);
    }
  }

  let payload: Record<string, unknown>;
  const contentType = request.headers.get("content-type") ?? "";
  try {
    if (contentType.includes("application/json")) {
      payload = (await request.json()) as Record<string, unknown>;
    } else {
      // Fallback path: a plain <form> POST with JS disabled arrives as
      // urlencoded/multipart. The form still works without JavaScript.
      const form = await request.formData();
      payload = Object.fromEntries(form.entries());
    }
  } catch {
    return json({ ok: false, error: "Could not read the submitted form." }, 400);
  }

  // Honeypot: a field hidden from humans via CSS. Bots fill every input they
  // find. Return a normal-looking success so the bot doesn't learn to adapt.
  if (clean(payload.website, 50) !== "") {
    return json({ ok: true }, 200);
  }

  const kind = clean(payload.kind, 40).toLowerCase();
  const message = clean(payload.message, MAX_MESSAGE);
  const entryRef = clean(payload.entry, MAX_SHORT_FIELD);
  const contact = clean(payload.contact, MAX_SHORT_FIELD);

  if (!KINDS.has(kind)) {
    return json({ ok: false, error: "Please choose what your request is about." }, 400);
  }
  if (message.length < 10) {
    return json(
      { ok: false, error: "Please describe the request in a little more detail." },
      400,
    );
  }

  try {
    const recent = await env.TAKEDOWNS.prepare(
      "SELECT COUNT(*) AS n FROM takedown_requests WHERE created_at > datetime('now', '-1 minute')",
    ).all<{ n: number }>();

    if ((recent.results[0]?.n ?? 0) >= MAX_PER_MINUTE) {
      return json(
        { ok: false, error: "Too many requests right now. Please try again shortly." },
        429,
      );
    }

    await env.TAKEDOWNS.prepare(
      `INSERT INTO takedown_requests (kind, entry_ref, contact, message, ip_country, user_agent)
       VALUES (?, ?, ?, ?, ?, ?)`,
    )
      .bind(
        kind,
        entryRef || null,
        contact || null,
        message,
        // Country only, never the IP itself. Enough to triage a flood, not
        // enough to identify someone reporting a problem with this archive —
        // which matters given what the archive is about.
        clean((request as { cf?: { country?: string } }).cf?.country, 8) || null,
        clean(request.headers.get("user-agent"), MAX_SHORT_FIELD) || null,
      )
      .run();
  } catch (error) {
    console.error("takedown insert failed", error);
    return json(
      { ok: false, error: "Something went wrong saving that. Please try again." },
      500,
    );
  }

  // No-JS path: a plain form POST expects a page back, not JSON. We can't
  // redirect to /takedown/?sent=1 and have it say anything useful — that page
  // is prerendered and static, so without JS it cannot read the query string.
  // So render the confirmation here instead.
  const accept = request.headers.get("accept") ?? "";
  if (!accept.includes("application/json")) {
    return new Response(CONFIRMATION_HTML, {
      status: 200,
      headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" },
    });
  }

  return json({ ok: true }, 200);
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const { pathname } = new URL(request.url);

    if (pathname === "/api/takedown") {
      return handleTakedown(request, env);
    }

    return env.ASSETS.fetch(request);
  },
};
